CREATE Table members (
  id BIGSERIAL PRIMARY KEY,
  mid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  nick_name VARCHAR(64) NOT NULL,
  gender VARCHAR(10) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
