// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/qhai-dev/galio/library/galio"
	"github.com/qhai-dev/galio/rpc/account/rpc"
	"github.com/qhai-dev/galio/rpc/account/rpc/handler"
)

// Injectors from wire.go:

func inject(application *galio.Application) (galio.Server, error) {
	rpcHandler := handler.NewHandler(application)
	server := rpc.New(rpcHandler)
	return server, nil
}
