// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: test2/v1/test2.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Test2Service_SayHello_FullMethodName      = "/test2.v1.Test2Service/SayHello"
	Test2Service_SayHelloAgain_FullMethodName = "/test2.v1.Test2Service/SayHelloAgain"
)

// Test2ServiceClient is the client API for Test2Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type Test2ServiceClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error)
	// Sends another greeting
	SayHelloAgain(ctx context.Context, in *SayHelloAgainRequest, opts ...grpc.CallOption) (*SayHelloAgainResponse, error)
}

type test2ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTest2ServiceClient(cc grpc.ClientConnInterface) Test2ServiceClient {
	return &test2ServiceClient{cc}
}

func (c *test2ServiceClient) SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SayHelloResponse)
	err := c.cc.Invoke(ctx, Test2Service_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *test2ServiceClient) SayHelloAgain(ctx context.Context, in *SayHelloAgainRequest, opts ...grpc.CallOption) (*SayHelloAgainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SayHelloAgainResponse)
	err := c.cc.Invoke(ctx, Test2Service_SayHelloAgain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Test2ServiceServer is the server API for Test2Service service.
// All implementations must embed UnimplementedTest2ServiceServer
// for forward compatibility.
//
// The greeting service definition.
type Test2ServiceServer interface {
	// Sends a greeting
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
	// Sends another greeting
	SayHelloAgain(context.Context, *SayHelloAgainRequest) (*SayHelloAgainResponse, error)
	mustEmbedUnimplementedTest2ServiceServer()
}

// UnimplementedTest2ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTest2ServiceServer struct{}

func (UnimplementedTest2ServiceServer) SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedTest2ServiceServer) SayHelloAgain(context.Context, *SayHelloAgainRequest) (*SayHelloAgainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SayHelloAgain not implemented")
}
func (UnimplementedTest2ServiceServer) mustEmbedUnimplementedTest2ServiceServer() {}
func (UnimplementedTest2ServiceServer) testEmbeddedByValue()                      {}

// UnsafeTest2ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Test2ServiceServer will
// result in compilation errors.
type UnsafeTest2ServiceServer interface {
	mustEmbedUnimplementedTest2ServiceServer()
}

func RegisterTest2ServiceServer(s grpc.ServiceRegistrar, srv Test2ServiceServer) {
	// If the following call panics, it indicates UnimplementedTest2ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Test2Service_ServiceDesc, srv)
}

func _Test2Service_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Test2ServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Test2Service_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Test2ServiceServer).SayHello(ctx, req.(*SayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test2Service_SayHelloAgain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloAgainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Test2ServiceServer).SayHelloAgain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Test2Service_SayHelloAgain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Test2ServiceServer).SayHelloAgain(ctx, req.(*SayHelloAgainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Test2Service_ServiceDesc is the grpc.ServiceDesc for Test2Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Test2Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test2.v1.Test2Service",
	HandlerType: (*Test2ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Test2Service_SayHello_Handler,
		},
		{
			MethodName: "SayHelloAgain",
			Handler:    _Test2Service_SayHelloAgain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test2/v1/test2.proto",
}
