// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: test2/v1/test2.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type SayHelloAgainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloAgainRequest) Reset() {
	*x = SayHelloAgainRequest{}
	mi := &file_test2_v1_test2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloAgainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloAgainRequest) ProtoMessage() {}

func (x *SayHelloAgainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test2_v1_test2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloAgainRequest.ProtoReflect.Descriptor instead.
func (*SayHelloAgainRequest) Descriptor() ([]byte, []int) {
	return file_test2_v1_test2_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloAgainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type SayHelloAgainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloAgainResponse) Reset() {
	*x = SayHelloAgainResponse{}
	mi := &file_test2_v1_test2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloAgainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloAgainResponse) ProtoMessage() {}

func (x *SayHelloAgainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test2_v1_test2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloAgainResponse.ProtoReflect.Descriptor instead.
func (*SayHelloAgainResponse) Descriptor() ([]byte, []int) {
	return file_test2_v1_test2_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloAgainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_test2_v1_test2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test2_v1_test2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_test2_v1_test2_proto_rawDescGZIP(), []int{2}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_test2_v1_test2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test2_v1_test2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_test2_v1_test2_proto_rawDescGZIP(), []int{3}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_test2_v1_test2_proto protoreflect.FileDescriptor

const file_test2_v1_test2_proto_rawDesc = "" +
	"\n" +
	"\x14test2/v1/test2.proto\x12\btest2.v1\"*\n" +
	"\x14SayHelloAgainRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"1\n" +
	"\x15SayHelloAgainResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\x0fSayHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10SayHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa7\x01\n" +
	"\fTest2Service\x12C\n" +
	"\bSayHello\x12\x19.test2.v1.SayHelloRequest\x1a\x1a.test2.v1.SayHelloResponse\"\x00\x12R\n" +
	"\rSayHelloAgain\x12\x1e.test2.v1.SayHelloAgainRequest\x1a\x1f.test2.v1.SayHelloAgainResponse\"\x00B2Z0github.com/qhai-dev/kairo/backend/kapis/test2/v1b\x06proto3"

var (
	file_test2_v1_test2_proto_rawDescOnce sync.Once
	file_test2_v1_test2_proto_rawDescData []byte
)

func file_test2_v1_test2_proto_rawDescGZIP() []byte {
	file_test2_v1_test2_proto_rawDescOnce.Do(func() {
		file_test2_v1_test2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test2_v1_test2_proto_rawDesc), len(file_test2_v1_test2_proto_rawDesc)))
	})
	return file_test2_v1_test2_proto_rawDescData
}

var file_test2_v1_test2_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_test2_v1_test2_proto_goTypes = []any{
	(*SayHelloAgainRequest)(nil),  // 0: test2.v1.SayHelloAgainRequest
	(*SayHelloAgainResponse)(nil), // 1: test2.v1.SayHelloAgainResponse
	(*SayHelloRequest)(nil),       // 2: test2.v1.SayHelloRequest
	(*SayHelloResponse)(nil),      // 3: test2.v1.SayHelloResponse
}
var file_test2_v1_test2_proto_depIdxs = []int32{
	2, // 0: test2.v1.Test2Service.SayHello:input_type -> test2.v1.SayHelloRequest
	0, // 1: test2.v1.Test2Service.SayHelloAgain:input_type -> test2.v1.SayHelloAgainRequest
	3, // 2: test2.v1.Test2Service.SayHello:output_type -> test2.v1.SayHelloResponse
	1, // 3: test2.v1.Test2Service.SayHelloAgain:output_type -> test2.v1.SayHelloAgainResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test2_v1_test2_proto_init() }
func file_test2_v1_test2_proto_init() {
	if File_test2_v1_test2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test2_v1_test2_proto_rawDesc), len(file_test2_v1_test2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test2_v1_test2_proto_goTypes,
		DependencyIndexes: file_test2_v1_test2_proto_depIdxs,
		MessageInfos:      file_test2_v1_test2_proto_msgTypes,
	}.Build()
	File_test2_v1_test2_proto = out.File
	file_test2_v1_test2_proto_goTypes = nil
	file_test2_v1_test2_proto_depIdxs = nil
}
